MVC_Examples/MyFirstMVCApplication/Models/DeveloperInformation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyFirstMVCApplication.Models
{
    public class DeveloperInformation
    {

        public string Name { get; set; }

        public DateTime CreationDate { get; set; }

        public DeveloperInformation()
        {
            Name = "";
            CreationDate = DateTime.Now;
        }

    }
}

MVC_Examples/MyFirstMVCApplication/Controllers/DeveloperInfoController.cs
using MyFirstMVCApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFirstMVCApplication.Controllers
{
    public class DeveloperInfoController : Controller
    {
        // GET: DeveloperInfo
        public ActionResult Index()
        {
            DeveloperInformation info = new DeveloperInformation();
            info.Name = "Adam Ackerman";
            
            return View(info);
        }

        public ActionResult EasyWay()
        {
            ViewBag.Message = "Wow, this way is a lot easier!";
            return View();
        }
    }
}

MVC_Examples/MyFirstMVCApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFirstMVCApplication.Controllers
{
    public class HomeController : Controller
    {
        //Home/Index
        public ActionResult Index()
        {
            return View();
        }

        //Home/About
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        //Home/Contact
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Adam()
        {
            ViewBag.Message = "This is the Adam Action at route Home/Adam";
            return View();
        }
    }
}

MVC_Examples/MyFirstMVCApplication/Views/DeveloperInfo/EasyWay.cshtml
@{
    ViewBag.Title = "EasyWay";
}

<h2>EasyWay</h2>

<p>@ViewBag.Message</p>

MVC_Examples/MyFirstMVCApplication/Views/DeveloperInfo/Index.cshtml
@model MyFirstMVCApplication.Models.DeveloperInformation

@{
    ViewBag.Title = "Developer Information";
}

<h2>Developer Information</h2>
<div>
    <h4>DeveloperInformation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

    </dl>
</div>

MVC_Examples/MyFirstMVCApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC_Examples/MyFirstMVCApplication/Views/Home/Adam.cshtml
@{
    ViewBag.Title = "Adam's Action";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Now we have an Adam <b>Action</b> on the <b>Home</b> controller!</p>

MVC_Examples/MyFirstMVCApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<h1 class="Contact_Header">This is our new contact information</h1>
<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC_Examples/MyFirstMVCApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVC_Examples/MyFirstMVCApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Adam", "Adam", "Home")</li>
                    <li>@Html.ActionLink("Developer Info", "Index", "DeveloperInfo")</li>
                    <li>@Html.ActionLink("Easy Way", "EasyWay", "DeveloperInfo")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>